export const Users = [
  {
    id: 0,
    userid: "y",
    device: "PC",
    gameTitle: "Apex",
    description: "Apex @1 gold3 ~",
    date: "12分前",
    photo: "/Pictures/hakone.png",
  },
  {
    id: 1,
    userid: "iiibk",
    device: "PC",
    gameTitle: "Apex",
    description:
      "アンレート @1 VC:discord アイアン〜シルバーくらいの方初心者歓迎です！ 雑談しながら楽しくやりましょう #VALORANT募集",
    date: "29分前",
    photo: "/Pictures/comme.png",
  },
  {
    id: 2,
    userid: "yuikuro",
    device: "PC",
    gameTitle: "Apex",
    description: "Apex @1 gold3 ~",
    date: "2分前",
    photo: "/Pictures/hakone.png",
  },
  {
    id: 3,
    userid: "yuikuro",
    device: "PC",
    gameTitle: "Apex",
    description: "Apex @1 gold3 ~",
    date: "1分前",
    photo: "/Pictures/panda.png",
  },
  {
    id: 4,
    userid: "ibkkk",
    device: "PC",
    gameTitle: "Apex",
    description: "Apex @1 gold3 ~",
    date: "9分前",
    photo: "/Pictures/hakone.png",
  },
  {
    id: 5,
    userid: "yuikuro",
    device: "PC",
    gameTitle: "Apex",
    description: "Apex @1 pratinum3 ~ plz",
    date: "33分前",
    photo: "/Pictures/comme.png",
  },
];
